# coding: utf-8

"""
    3DI API

    3DI simulation API  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Progress(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'simulation': 'str',
        'created': 'datetime',
        'integer_percentage': 'str',
        'timestep': 'int'
    }

    attribute_map = {
        'url': 'url',
        'simulation': 'simulation',
        'created': 'created',
        'integer_percentage': 'integer_percentage',
        'timestep': 'timestep'
    }

    def __init__(self, url=None, simulation=None, created=None, integer_percentage=None, timestep=None):  # noqa: E501
        """Progress - a model defined in OpenAPI"""  # noqa: E501

        self._url = None
        self._simulation = None
        self._created = None
        self._integer_percentage = None
        self._timestep = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if simulation is not None:
            self.simulation = simulation
        if created is not None:
            self.created = created
        if integer_percentage is not None:
            self.integer_percentage = integer_percentage
        self.timestep = timestep

    @property
    def url(self):
        """Gets the url of this Progress.  # noqa: E501


        :return: The url of this Progress.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Progress.


        :param url: The url of this Progress.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def simulation(self):
        """Gets the simulation of this Progress.  # noqa: E501


        :return: The simulation of this Progress.  # noqa: E501
        :rtype: str
        """
        return self._simulation

    @simulation.setter
    def simulation(self, simulation):
        """Sets the simulation of this Progress.


        :param simulation: The simulation of this Progress.  # noqa: E501
        :type: str
        """

        self._simulation = simulation

    @property
    def created(self):
        """Gets the created of this Progress.  # noqa: E501


        :return: The created of this Progress.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Progress.


        :param created: The created of this Progress.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def integer_percentage(self):
        """Gets the integer_percentage of this Progress.  # noqa: E501


        :return: The integer_percentage of this Progress.  # noqa: E501
        :rtype: str
        """
        return self._integer_percentage

    @integer_percentage.setter
    def integer_percentage(self, integer_percentage):
        """Sets the integer_percentage of this Progress.


        :param integer_percentage: The integer_percentage of this Progress.  # noqa: E501
        :type: str
        """

        self._integer_percentage = integer_percentage

    @property
    def timestep(self):
        """Gets the timestep of this Progress.  # noqa: E501


        :return: The timestep of this Progress.  # noqa: E501
        :rtype: int
        """
        return self._timestep

    @timestep.setter
    def timestep(self, timestep):
        """Sets the timestep of this Progress.


        :param timestep: The timestep of this Progress.  # noqa: E501
        :type: int
        """
        if timestep is None:
            raise ValueError("Invalid value for `timestep`, must not be `None`")  # noqa: E501
        if timestep is not None and timestep > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `timestep`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if timestep is not None and timestep < 0:  # noqa: E501
            raise ValueError("Invalid value for `timestep`, must be a value greater than or equal to `0`")  # noqa: E501

        self._timestep = timestep

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Progress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
