# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class Action(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'ActionNameEnum',
        'duration': 'int',
        'timeout': 'int',
        'max_rate': 'float',
        'compute_cluster': 'str',
        'simulation_runner': 'SimulationRunnerEnum'
    }

    attribute_map = {
        'name': 'name',
        'duration': 'duration',
        'timeout': 'timeout',
        'max_rate': 'max_rate',
        'compute_cluster': 'compute_cluster',
        'simulation_runner': 'simulation_runner'
    }

    def __init__(self, name=None, duration=None, timeout=300, max_rate=None, compute_cluster=None, simulation_runner=None, local_vars_configuration=None):  # noqa: E501
        """Action - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._duration = None
        self._timeout = None
        self._max_rate = None
        self._compute_cluster = None
        self._simulation_runner = None
        self.discriminator = None

        self.name = name
        if duration is not None:
            self.duration = duration
        if timeout is not None:
            self.timeout = timeout
        if max_rate is not None:
            self.max_rate = max_rate
        if compute_cluster is not None:
            self.compute_cluster = compute_cluster
        self.simulation_runner = simulation_runner

    @property
    def name(self):
        """Gets the name of this Action.  # noqa: E501


        :return: The name of this Action.  # noqa: E501
        :rtype: ActionNameEnum
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Action.


        :param name: The name of this Action.  # noqa: E501
        :type name: ActionNameEnum
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def duration(self):
        """Gets the duration of this Action.  # noqa: E501

        Only valid for name='start'. Run simulation for given duration (in seconds) and pause  # noqa: E501

        :return: The duration of this Action.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Action.

        Only valid for name='start'. Run simulation for given duration (in seconds) and pause  # noqa: E501

        :param duration: The duration of this Action.  # noqa: E501
        :type duration: int
        """
        if (self.local_vars_configuration.client_side_validation and
                duration is not None and duration < 1):  # noqa: E501
            raise ValueError("Invalid value for `duration`, must be a value greater than or equal to `1`")  # noqa: E501

        self._duration = duration

    @property
    def timeout(self):
        """Gets the timeout of this Action.  # noqa: E501

        Only valid for name='pause'. Remove simulation after given timeout (in seconds). Defaults to 300 seconds  # noqa: E501

        :return: The timeout of this Action.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this Action.

        Only valid for name='pause'. Remove simulation after given timeout (in seconds). Defaults to 300 seconds  # noqa: E501

        :param timeout: The timeout of this Action.  # noqa: E501
        :type timeout: int
        """
        if (self.local_vars_configuration.client_side_validation and
                timeout is not None and timeout < 30):  # noqa: E501
            raise ValueError("Invalid value for `timeout`, must be a value greater than or equal to `30`")  # noqa: E501

        self._timeout = timeout

    @property
    def max_rate(self):
        """Gets the max_rate of this Action.  # noqa: E501

        Only valid for name='start'. Limit maximum speed of the simulation. The max_rate is a multiplier relative to real time For example max_rate '60' means max 60 simulation seconds in 1 real second   # noqa: E501

        :return: The max_rate of this Action.  # noqa: E501
        :rtype: float
        """
        return self._max_rate

    @max_rate.setter
    def max_rate(self, max_rate):
        """Sets the max_rate of this Action.

        Only valid for name='start'. Limit maximum speed of the simulation. The max_rate is a multiplier relative to real time For example max_rate '60' means max 60 simulation seconds in 1 real second   # noqa: E501

        :param max_rate: The max_rate of this Action.  # noqa: E501
        :type max_rate: float
        """
        if (self.local_vars_configuration.client_side_validation and
                max_rate is not None and max_rate < 1):  # noqa: E501
            raise ValueError("Invalid value for `max_rate`, must be a value greater than or equal to `1`")  # noqa: E501

        self._max_rate = max_rate

    @property
    def compute_cluster(self):
        """Gets the compute_cluster of this Action.  # noqa: E501

        Only valid for name values: 'start', 'initialize' or 'queue' Compute cluster to start the session. If ommitted the first available cluster is used, starting with the default cluster.  # noqa: E501

        :return: The compute_cluster of this Action.  # noqa: E501
        :rtype: str
        """
        return self._compute_cluster

    @compute_cluster.setter
    def compute_cluster(self, compute_cluster):
        """Sets the compute_cluster of this Action.

        Only valid for name values: 'start', 'initialize' or 'queue' Compute cluster to start the session. If ommitted the first available cluster is used, starting with the default cluster.  # noqa: E501

        :param compute_cluster: The compute_cluster of this Action.  # noqa: E501
        :type compute_cluster: str
        """

        self._compute_cluster = compute_cluster

    @property
    def simulation_runner(self):
        """Gets the simulation_runner of this Action.  # noqa: E501

        Only allowed for name values: 'start', 'initialize' or 'queue Simulation runner version used to execute the simulation. If not filled in the default version is used. (Note: used for testing new calccore releases on the staging environment. On production only the default version can be picked)  * `3.4.104-3.7.2` - 3.4.104-3.7.2 * `3.2.17-2.3.6` - 3.2.17-2.3.6  # noqa: E501

        :return: The simulation_runner of this Action.  # noqa: E501
        :rtype: SimulationRunnerEnum
        """
        return self._simulation_runner

    @simulation_runner.setter
    def simulation_runner(self, simulation_runner):
        """Sets the simulation_runner of this Action.

        Only allowed for name values: 'start', 'initialize' or 'queue Simulation runner version used to execute the simulation. If not filled in the default version is used. (Note: used for testing new calccore releases on the staging environment. On production only the default version can be picked)  * `3.4.104-3.7.2` - 3.4.104-3.7.2 * `3.2.17-2.3.6` - 3.2.17-2.3.6  # noqa: E501

        :param simulation_runner: The simulation_runner of this Action.  # noqa: E501
        :type simulation_runner: SimulationRunnerEnum
        """

        self._simulation_runner = simulation_runner

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Action):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Action):
            return True

        return self.to_dict() != other.to_dict()
