# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class Download(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'get_url': 'str',
        'is_internal': 'bool',
        'etag': 'str',
        'size': 'int'
    }

    attribute_map = {
        'get_url': 'get_url',
        'is_internal': 'is_internal',
        'etag': 'etag',
        'size': 'size'
    }

    def __init__(self, get_url=None, is_internal=True, etag=None, size=None, local_vars_configuration=None):  # noqa: E501
        """Download - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._get_url = None
        self._is_internal = None
        self._etag = None
        self._size = None
        self.discriminator = None

        if get_url is not None:
            self.get_url = get_url
        if is_internal is not None:
            self.is_internal = is_internal
        self.etag = etag
        self.size = size

    @property
    def get_url(self):
        """Gets the get_url of this Download.  # noqa: E501


        :return: The get_url of this Download.  # noqa: E501
        :rtype: str
        """
        return self._get_url

    @get_url.setter
    def get_url(self, get_url):
        """Sets the get_url of this Download.


        :param get_url: The get_url of this Download.  # noqa: E501
        :type get_url: str
        """

        self._get_url = get_url

    @property
    def is_internal(self):
        """Gets the is_internal of this Download.  # noqa: E501


        :return: The is_internal of this Download.  # noqa: E501
        :rtype: bool
        """
        return self._is_internal

    @is_internal.setter
    def is_internal(self, is_internal):
        """Sets the is_internal of this Download.


        :param is_internal: The is_internal of this Download.  # noqa: E501
        :type is_internal: bool
        """

        self._is_internal = is_internal

    @property
    def etag(self):
        """Gets the etag of this Download.  # noqa: E501

        Optional eTag (md5sum)  # noqa: E501

        :return: The etag of this Download.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this Download.

        Optional eTag (md5sum)  # noqa: E501

        :param etag: The etag of this Download.  # noqa: E501
        :type etag: str
        """

        self._etag = etag

    @property
    def size(self):
        """Gets the size of this Download.  # noqa: E501

        Filesize in bytes  # noqa: E501

        :return: The size of this Download.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this Download.

        Filesize in bytes  # noqa: E501

        :param size: The size of this Download.  # noqa: E501
        :type size: int
        """

        self._size = size

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Download):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Download):
            return True

        return self.to_dict() != other.to_dict()
