# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  12:08PM (UTC) on June 11, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import logging
import pprint
import re  # noqa: F401

import six

from threedi_api_client.openapi.configuration import Configuration

logger = logging.getLogger(__name__)

class ExitCodeEnum(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    USER_SHUTDOWN_PREMATURE = 1110
    USER_SHUTDOWN = 1210
    FINISHED = 1240
    HEALTH_CHECK_PREMATURE_CONTAINER_ERROR = 4161
    HEALTH_CHECK_CONTAINER_ERROR = 4262
    HEALTH_CHECK_INITIALIZED_ERROR = 4263
    HEALTH_CHECK_ENDED_ERROR = 4264
    HEALTH_CHECK_POSTPROCESSING_ERROR = 4265
    INITIAL_CONDITION_WORKER_ERROR = 4120
    EVENT_WORKER_ERROR = 4220
    CONTAINER_STARTUP_ERROR = 4150
    OUT_OF_RESOURCES = 4280
    CALCULATION_CORE_ERROR = 4240
    CALCULATION_PYTHON_ERROR = 4270
    API_RESSOURCE_ERROR = 4230
    UPLOAD_REQUEST_ERROR = 4231
    UNFINISHED_TASKS_ERROR = 4232
    IGNITION_TIMEOUT = 2150
    INITIALIZED_PAUSED_TIMEOUT = 2110
    PAUSED_TIMEOUT = 2210
    INITIAL_CONDITION_WORKER_TIMEOUT = 2120
    EVENT_WORKER_TIMEOUT = 2220
    ENQUE_ACTION_COLLECTION_TIMEOUT = 2230
    CLEAR_EVENT_DATA_TIMEOUT = 2240

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    required_fields = [
    ]

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None, fetched_from_api=False):  # noqa: E501
        """ExitCodeEnum - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        # True if data is coming from API
        self._fetched_from_api = fetched_from_api
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def __handle_validation_error(self, message):
        # Only raise ValueError when not fetched from API
        try:
            from threedi_api_client import __version__ as VERSION
        except ImportError:
            VERSION = "unknown"

        if not self._fetched_from_api:
            raise ValueError(message + f" It is possible that the current threedi-api-client version ({VERSION}) is out of date: consult https://pypi.org/project/threedi-api-client/ and consider upgrading.")  # noqa: E501
        logger.warning(message + " Please update to the latest threedi-api-client version.")  # noqa: E501

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExitCodeEnum):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExitCodeEnum):
            return True

        return self.to_dict() != other.to_dict()
