# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  02:13PM (UTC) on June 09, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import logging
import pprint
import re  # noqa: F401

import six

from threedi_api_client.openapi.configuration import Configuration

logger = logging.getLogger(__name__)

class ExitCodeEnum(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _1110 = "1110"
    _1210 = "1210"
    _1240 = "1240"
    _4161 = "4161"
    _4262 = "4262"
    _4263 = "4263"
    _4264 = "4264"
    _4265 = "4265"
    _4120 = "4120"
    _4220 = "4220"
    _4150 = "4150"
    _4280 = "4280"
    _4240 = "4240"
    _4270 = "4270"
    _4230 = "4230"
    _4231 = "4231"
    _4232 = "4232"
    _2150 = "2150"
    _2110 = "2110"
    _2210 = "2210"
    _2120 = "2120"
    _2220 = "2220"
    _2230 = "2230"
    _2240 = "2240"

    allowable_values = [_1110, _1210, _1240, _4161, _4262, _4263, _4264, _4265, _4120, _4220, _4150, _4280, _4240, _4270, _4230, _4231, _4232, _2150, _2110, _2210, _2120, _2220, _2230, _2240]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    required_fields = [
    ]

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None, fetched_from_api=False):  # noqa: E501
        """ExitCodeEnum - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        # True if data is coming from API
        self._fetched_from_api = fetched_from_api
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def __handle_validation_error(self, message):
        # Only raise ValueError when not fetched from API
        from threedi_api_client import __version__ as VERSION

        if not self._fetched_from_api:
            raise ValueError(message + f" It is possible that the current threedi-api-client version ({VERSION}) is out of date: consult https://pypi.org/project/threedi-api-client/ and consider upgrading.")  # noqa: E501
        logger.warning(message + " Please update to the latest threedi-api-client version.")  # noqa: E501

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExitCodeEnum):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExitCodeEnum):
            return True

        return self.to_dict() != other.to_dict()
