# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class OrganisationSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'historical_rain_radar_uuids': 'list[str]',
        'forecast_rain_radar_uuids': 'list[str]'
    }

    attribute_map = {
        'historical_rain_radar_uuids': 'historical_rain_radar_uuids',
        'forecast_rain_radar_uuids': 'forecast_rain_radar_uuids'
    }

    def __init__(self, historical_rain_radar_uuids=None, forecast_rain_radar_uuids=None, local_vars_configuration=None):  # noqa: E501
        """OrganisationSettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._historical_rain_radar_uuids = None
        self._forecast_rain_radar_uuids = None
        self.discriminator = None

        if historical_rain_radar_uuids is not None:
            self.historical_rain_radar_uuids = historical_rain_radar_uuids
        if forecast_rain_radar_uuids is not None:
            self.forecast_rain_radar_uuids = forecast_rain_radar_uuids

    @property
    def historical_rain_radar_uuids(self):
        """Gets the historical_rain_radar_uuids of this OrganisationSettings.  # noqa: E501


        :return: The historical_rain_radar_uuids of this OrganisationSettings.  # noqa: E501
        :rtype: list[str]
        """
        return self._historical_rain_radar_uuids

    @historical_rain_radar_uuids.setter
    def historical_rain_radar_uuids(self, historical_rain_radar_uuids):
        """Sets the historical_rain_radar_uuids of this OrganisationSettings.


        :param historical_rain_radar_uuids: The historical_rain_radar_uuids of this OrganisationSettings.  # noqa: E501
        :type historical_rain_radar_uuids: list[str]
        """

        self._historical_rain_radar_uuids = historical_rain_radar_uuids

    @property
    def forecast_rain_radar_uuids(self):
        """Gets the forecast_rain_radar_uuids of this OrganisationSettings.  # noqa: E501


        :return: The forecast_rain_radar_uuids of this OrganisationSettings.  # noqa: E501
        :rtype: list[str]
        """
        return self._forecast_rain_radar_uuids

    @forecast_rain_radar_uuids.setter
    def forecast_rain_radar_uuids(self, forecast_rain_radar_uuids):
        """Sets the forecast_rain_radar_uuids of this OrganisationSettings.


        :param forecast_rain_radar_uuids: The forecast_rain_radar_uuids of this OrganisationSettings.  # noqa: E501
        :type forecast_rain_radar_uuids: list[str]
        """

        self._forecast_rain_radar_uuids = forecast_rain_radar_uuids

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganisationSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganisationSettings):
            return True

        return self.to_dict() != other.to_dict()
