# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  02:28PM (UTC) on June 08, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import logging
import pprint
import re  # noqa: F401

import six

from threedi_api_client.openapi.configuration import Configuration

logger = logging.getLogger(__name__)

class PatchedPhysicalSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'simulation_id': 'int',
        'use_advection_1d': 'UseAdvection1dEnum',
        'use_advection_2d': 'UsePreconditionerCgEnum'
    }

    required_fields = [
    ]

    attribute_map = {
        'id': 'id',
        'simulation_id': 'simulation_id',
        'use_advection_1d': 'use_advection_1d',
        'use_advection_2d': 'use_advection_2d'
    }

    def __init__(self, id=None, simulation_id=None, use_advection_1d=None, use_advection_2d=None, local_vars_configuration=None, fetched_from_api=False):  # noqa: E501
        """PatchedPhysicalSettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        # True if data is coming from API
        self._fetched_from_api = fetched_from_api

        self._id = None
        self._simulation_id = None
        self._use_advection_1d = None
        self._use_advection_2d = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if simulation_id is not None:
            self.simulation_id = simulation_id
        if use_advection_1d is not None:
            self.use_advection_1d = use_advection_1d
        if use_advection_2d is not None:
            self.use_advection_2d = use_advection_2d

    @property
    def id(self):
        """Gets the id of this PatchedPhysicalSettings.  # noqa: E501


        :return: The id of this PatchedPhysicalSettings.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedPhysicalSettings.


        :param id: The id of this PatchedPhysicalSettings.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def simulation_id(self):
        """Gets the simulation_id of this PatchedPhysicalSettings.  # noqa: E501


        :return: The simulation_id of this PatchedPhysicalSettings.  # noqa: E501
        :rtype: int
        """
        return self._simulation_id

    @simulation_id.setter
    def simulation_id(self, simulation_id):
        """Sets the simulation_id of this PatchedPhysicalSettings.


        :param simulation_id: The simulation_id of this PatchedPhysicalSettings.  # noqa: E501
        :type: int
        """

        self._simulation_id = simulation_id

    @property
    def use_advection_1d(self):
        """Gets the use_advection_1d of this PatchedPhysicalSettings.  # noqa: E501

        Options:  0 = off 1 = momentum conservative 2 = energy conservative 3 = combined momentum and energy conservative   * `0` - off * `1` - momentum conservative * `2` - energy conservative * `3` - combined momentum and energy conservative  # noqa: E501

        :return: The use_advection_1d of this PatchedPhysicalSettings.  # noqa: E501
        :rtype: UseAdvection1dEnum
        """
        return self._use_advection_1d

    @use_advection_1d.setter
    def use_advection_1d(self, use_advection_1d):
        """Sets the use_advection_1d of this PatchedPhysicalSettings.

        Options:  0 = off 1 = momentum conservative 2 = energy conservative 3 = combined momentum and energy conservative   * `0` - off * `1` - momentum conservative * `2` - energy conservative * `3` - combined momentum and energy conservative  # noqa: E501

        :param use_advection_1d: The use_advection_1d of this PatchedPhysicalSettings.  # noqa: E501
        :type: UseAdvection1dEnum
        """

        self._use_advection_1d = use_advection_1d

    @property
    def use_advection_2d(self):
        """Gets the use_advection_2d of this PatchedPhysicalSettings.  # noqa: E501

        Options:  0 = off 1 = standard   * `0` - off * `1` - standard  # noqa: E501

        :return: The use_advection_2d of this PatchedPhysicalSettings.  # noqa: E501
        :rtype: UsePreconditionerCgEnum
        """
        return self._use_advection_2d

    @use_advection_2d.setter
    def use_advection_2d(self, use_advection_2d):
        """Sets the use_advection_2d of this PatchedPhysicalSettings.

        Options:  0 = off 1 = standard   * `0` - off * `1` - standard  # noqa: E501

        :param use_advection_2d: The use_advection_2d of this PatchedPhysicalSettings.  # noqa: E501
        :type: UsePreconditionerCgEnum
        """

        self._use_advection_2d = use_advection_2d

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def __handle_validation_error(self, message):
        # Only raise ValueError when not fetched from API
        from threedi_api_client import __version__ as VERSION

        if not self._fetched_from_api:
            raise ValueError(message + f" It is possible that the current threedi-api-client version ({VERSION}) is out of date: consult https://pypi.org/project/threedi-api-client/ and consider upgrading.")  # noqa: E501
        logger.warning(message + " Please update to the latest threedi-api-client version.")  # noqa: E501

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedPhysicalSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchedPhysicalSettings):
            return True

        return self.to_dict() != other.to_dict()
