# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class PatchedFile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'storage_name': 'str',
        'filename': 'str',
        'bucket': 'str',
        'prefix': 'str',
        'etag': 'str',
        'size': 'int',
        'expiry_date': 'date',
        'related_object': 'str',
        'type': 'UploadTypeEnum',
        'state': 'FileStateEnum',
        'state_description': 'str',
        'meta': 'object',
        'id': 'int'
    }

    attribute_map = {
        'url': 'url',
        'storage_name': 'storage_name',
        'filename': 'filename',
        'bucket': 'bucket',
        'prefix': 'prefix',
        'etag': 'etag',
        'size': 'size',
        'expiry_date': 'expiry_date',
        'related_object': 'related_object',
        'type': 'type',
        'state': 'state',
        'state_description': 'state_description',
        'meta': 'meta',
        'id': 'id'
    }

    def __init__(self, url=None, storage_name=None, filename=None, bucket=None, prefix=None, etag=None, size=None, expiry_date=None, related_object=None, type=None, state=None, state_description=None, meta=None, id=None, local_vars_configuration=None):  # noqa: E501
        """PatchedFile - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._url = None
        self._storage_name = None
        self._filename = None
        self._bucket = None
        self._prefix = None
        self._etag = None
        self._size = None
        self._expiry_date = None
        self._related_object = None
        self._type = None
        self._state = None
        self._state_description = None
        self._meta = None
        self._id = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if storage_name is not None:
            self.storage_name = storage_name
        if filename is not None:
            self.filename = filename
        if bucket is not None:
            self.bucket = bucket
        self.prefix = prefix
        self.etag = etag
        self.size = size
        if expiry_date is not None:
            self.expiry_date = expiry_date
        if related_object is not None:
            self.related_object = related_object
        if type is not None:
            self.type = type
        if state is not None:
            self.state = state
        self.state_description = state_description
        self.meta = meta
        if id is not None:
            self.id = id

    @property
    def url(self):
        """Gets the url of this PatchedFile.  # noqa: E501


        :return: The url of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this PatchedFile.


        :param url: The url of this PatchedFile.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def storage_name(self):
        """Gets the storage_name of this PatchedFile.  # noqa: E501


        :return: The storage_name of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._storage_name

    @storage_name.setter
    def storage_name(self, storage_name):
        """Sets the storage_name of this PatchedFile.


        :param storage_name: The storage_name of this PatchedFile.  # noqa: E501
        :type storage_name: str
        """

        self._storage_name = storage_name

    @property
    def filename(self):
        """Gets the filename of this PatchedFile.  # noqa: E501


        :return: The filename of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this PatchedFile.


        :param filename: The filename of this PatchedFile.  # noqa: E501
        :type filename: str
        """
        if (self.local_vars_configuration.client_side_validation and
                filename is not None and len(filename) > 256):
            raise ValueError("Invalid value for `filename`, length must be less than or equal to `256`")  # noqa: E501

        self._filename = filename

    @property
    def bucket(self):
        """Gets the bucket of this PatchedFile.  # noqa: E501


        :return: The bucket of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this PatchedFile.


        :param bucket: The bucket of this PatchedFile.  # noqa: E501
        :type bucket: str
        """
        if (self.local_vars_configuration.client_side_validation and
                bucket is not None and len(bucket) > 256):
            raise ValueError("Invalid value for `bucket`, length must be less than or equal to `256`")  # noqa: E501

        self._bucket = bucket

    @property
    def prefix(self):
        """Gets the prefix of this PatchedFile.  # noqa: E501


        :return: The prefix of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this PatchedFile.


        :param prefix: The prefix of this PatchedFile.  # noqa: E501
        :type prefix: str
        """
        if (self.local_vars_configuration.client_side_validation and
                prefix is not None and len(prefix) > 256):
            raise ValueError("Invalid value for `prefix`, length must be less than or equal to `256`")  # noqa: E501

        self._prefix = prefix

    @property
    def etag(self):
        """Gets the etag of this PatchedFile.  # noqa: E501

        Optional eTag (md5sum)  # noqa: E501

        :return: The etag of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this PatchedFile.

        Optional eTag (md5sum)  # noqa: E501

        :param etag: The etag of this PatchedFile.  # noqa: E501
        :type etag: str
        """
        if (self.local_vars_configuration.client_side_validation and
                etag is not None and len(etag) > 256):
            raise ValueError("Invalid value for `etag`, length must be less than or equal to `256`")  # noqa: E501

        self._etag = etag

    @property
    def size(self):
        """Gets the size of this PatchedFile.  # noqa: E501

        Filesize in bytes  # noqa: E501

        :return: The size of this PatchedFile.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this PatchedFile.

        Filesize in bytes  # noqa: E501

        :param size: The size of this PatchedFile.  # noqa: E501
        :type size: int
        """
        if (self.local_vars_configuration.client_side_validation and
                size is not None and size > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `size`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                size is not None and size < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `size`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._size = size

    @property
    def expiry_date(self):
        """Gets the expiry_date of this PatchedFile.  # noqa: E501


        :return: The expiry_date of this PatchedFile.  # noqa: E501
        :rtype: date
        """
        return self._expiry_date

    @expiry_date.setter
    def expiry_date(self, expiry_date):
        """Sets the expiry_date of this PatchedFile.


        :param expiry_date: The expiry_date of this PatchedFile.  # noqa: E501
        :type expiry_date: date
        """

        self._expiry_date = expiry_date

    @property
    def related_object(self):
        """Gets the related_object of this PatchedFile.  # noqa: E501


        :return: The related_object of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._related_object

    @related_object.setter
    def related_object(self, related_object):
        """Sets the related_object of this PatchedFile.


        :param related_object: The related_object of this PatchedFile.  # noqa: E501
        :type related_object: str
        """

        self._related_object = related_object

    @property
    def type(self):
        """Gets the type of this PatchedFile.  # noqa: E501


        :return: The type of this PatchedFile.  # noqa: E501
        :rtype: UploadTypeEnum
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PatchedFile.


        :param type: The type of this PatchedFile.  # noqa: E501
        :type type: UploadTypeEnum
        """

        self._type = type

    @property
    def state(self):
        """Gets the state of this PatchedFile.  # noqa: E501


        :return: The state of this PatchedFile.  # noqa: E501
        :rtype: FileStateEnum
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this PatchedFile.


        :param state: The state of this PatchedFile.  # noqa: E501
        :type state: FileStateEnum
        """

        self._state = state

    @property
    def state_description(self):
        """Gets the state_description of this PatchedFile.  # noqa: E501


        :return: The state_description of this PatchedFile.  # noqa: E501
        :rtype: str
        """
        return self._state_description

    @state_description.setter
    def state_description(self, state_description):
        """Sets the state_description of this PatchedFile.


        :param state_description: The state_description of this PatchedFile.  # noqa: E501
        :type state_description: str
        """
        if (self.local_vars_configuration.client_side_validation and
                state_description is not None and len(state_description) > 512):
            raise ValueError("Invalid value for `state_description`, length must be less than or equal to `512`")  # noqa: E501

        self._state_description = state_description

    @property
    def meta(self):
        """Gets the meta of this PatchedFile.  # noqa: E501


        :return: The meta of this PatchedFile.  # noqa: E501
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this PatchedFile.


        :param meta: The meta of this PatchedFile.  # noqa: E501
        :type meta: object
        """

        self._meta = meta

    @property
    def id(self):
        """Gets the id of this PatchedFile.  # noqa: E501


        :return: The id of this PatchedFile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedFile.


        :param id: The id of this PatchedFile.  # noqa: E501
        :type id: int
        """

        self._id = id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedFile):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchedFile):
            return True

        return self.to_dict() != other.to_dict()
