# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class PatchedRaster(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'type': 'RasterTypeEnum',
        'threedimodel': 'str',
        'name': 'str',
        'file': 'FileReadOnly',
        'id': 'int',
        'epsg_code': 'int',
        'extent': 'Extent',
        'geotransform': 'list[float]',
        'unit': 'UnitEnum'
    }

    attribute_map = {
        'url': 'url',
        'type': 'type',
        'threedimodel': 'threedimodel',
        'name': 'name',
        'file': 'file',
        'id': 'id',
        'epsg_code': 'epsg_code',
        'extent': 'extent',
        'geotransform': 'geotransform',
        'unit': 'unit'
    }

    def __init__(self, url=None, type=None, threedimodel=None, name=None, file=None, id=None, epsg_code=None, extent=None, geotransform=None, unit=None, local_vars_configuration=None):  # noqa: E501
        """PatchedRaster - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._url = None
        self._type = None
        self._threedimodel = None
        self._name = None
        self._file = None
        self._id = None
        self._epsg_code = None
        self._extent = None
        self._geotransform = None
        self._unit = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if type is not None:
            self.type = type
        self.threedimodel = threedimodel
        if name is not None:
            self.name = name
        self.file = file
        if id is not None:
            self.id = id
        self.epsg_code = epsg_code
        if extent is not None:
            self.extent = extent
        self.geotransform = geotransform
        if unit is not None:
            self.unit = unit

    @property
    def url(self):
        """Gets the url of this PatchedRaster.  # noqa: E501


        :return: The url of this PatchedRaster.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this PatchedRaster.


        :param url: The url of this PatchedRaster.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def type(self):
        """Gets the type of this PatchedRaster.  # noqa: E501


        :return: The type of this PatchedRaster.  # noqa: E501
        :rtype: RasterTypeEnum
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PatchedRaster.


        :param type: The type of this PatchedRaster.  # noqa: E501
        :type type: RasterTypeEnum
        """

        self._type = type

    @property
    def threedimodel(self):
        """Gets the threedimodel of this PatchedRaster.  # noqa: E501


        :return: The threedimodel of this PatchedRaster.  # noqa: E501
        :rtype: str
        """
        return self._threedimodel

    @threedimodel.setter
    def threedimodel(self, threedimodel):
        """Sets the threedimodel of this PatchedRaster.


        :param threedimodel: The threedimodel of this PatchedRaster.  # noqa: E501
        :type threedimodel: str
        """

        self._threedimodel = threedimodel

    @property
    def name(self):
        """Gets the name of this PatchedRaster.  # noqa: E501


        :return: The name of this PatchedRaster.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PatchedRaster.


        :param name: The name of this PatchedRaster.  # noqa: E501
        :type name: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 60):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `60`")  # noqa: E501

        self._name = name

    @property
    def file(self):
        """Gets the file of this PatchedRaster.  # noqa: E501


        :return: The file of this PatchedRaster.  # noqa: E501
        :rtype: FileReadOnly
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this PatchedRaster.


        :param file: The file of this PatchedRaster.  # noqa: E501
        :type file: FileReadOnly
        """

        self._file = file

    @property
    def id(self):
        """Gets the id of this PatchedRaster.  # noqa: E501


        :return: The id of this PatchedRaster.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedRaster.


        :param id: The id of this PatchedRaster.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def epsg_code(self):
        """Gets the epsg_code of this PatchedRaster.  # noqa: E501


        :return: The epsg_code of this PatchedRaster.  # noqa: E501
        :rtype: int
        """
        return self._epsg_code

    @epsg_code.setter
    def epsg_code(self, epsg_code):
        """Sets the epsg_code of this PatchedRaster.


        :param epsg_code: The epsg_code of this PatchedRaster.  # noqa: E501
        :type epsg_code: int
        """
        if (self.local_vars_configuration.client_side_validation and
                epsg_code is not None and epsg_code > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `epsg_code`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                epsg_code is not None and epsg_code < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `epsg_code`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._epsg_code = epsg_code

    @property
    def extent(self):
        """Gets the extent of this PatchedRaster.  # noqa: E501


        :return: The extent of this PatchedRaster.  # noqa: E501
        :rtype: Extent
        """
        return self._extent

    @extent.setter
    def extent(self, extent):
        """Sets the extent of this PatchedRaster.


        :param extent: The extent of this PatchedRaster.  # noqa: E501
        :type extent: Extent
        """

        self._extent = extent

    @property
    def geotransform(self):
        """Gets the geotransform of this PatchedRaster.  # noqa: E501


        :return: The geotransform of this PatchedRaster.  # noqa: E501
        :rtype: list[float]
        """
        return self._geotransform

    @geotransform.setter
    def geotransform(self, geotransform):
        """Sets the geotransform of this PatchedRaster.


        :param geotransform: The geotransform of this PatchedRaster.  # noqa: E501
        :type geotransform: list[float]
        """
        if (self.local_vars_configuration.client_side_validation and
                geotransform is not None and len(geotransform) > 6):
            raise ValueError("Invalid value for `geotransform`, number of items must be less than or equal to `6`")  # noqa: E501

        self._geotransform = geotransform

    @property
    def unit(self):
        """Gets the unit of this PatchedRaster.  # noqa: E501


        :return: The unit of this PatchedRaster.  # noqa: E501
        :rtype: UnitEnum
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this PatchedRaster.


        :param unit: The unit of this PatchedRaster.  # noqa: E501
        :type unit: UnitEnum
        """

        self._unit = unit

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedRaster):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchedRaster):
            return True

        return self.to_dict() != other.to_dict()
