# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.5.8   Rana simulation core release: 3.7.2   deployed on:  09:08AM (UTC) on June 24, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import logging
import pprint
import re  # noqa: F401

import six

from threedi_api_client.openapi.configuration import Configuration

logger = logging.getLogger(__name__)

class PatchedTimeseriesLocalRain(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'simulation': 'str',
        'offset': 'int',
        'values': 'list[list[float]]',
        'interpolate': 'bool',
        'units': 'LocalRainUnitEnum',
        'diameter': 'int',
        'point': 'Point',
        'uid': 'str',
        'id': 'int',
        'substances': 'list[ForcingSubstanceWithZone]'
    }

    required_fields = [
    ]

    attribute_map = {
        'url': 'url',
        'simulation': 'simulation',
        'offset': 'offset',
        'values': 'values',
        'interpolate': 'interpolate',
        'units': 'units',
        'diameter': 'diameter',
        'point': 'point',
        'uid': 'uid',
        'id': 'id',
        'substances': 'substances'
    }

    def __init__(self, url=None, simulation=None, offset=None, values=None, interpolate=None, units=None, diameter=None, point=None, uid=None, id=None, substances=None, local_vars_configuration=None, fetched_from_api=False):  # noqa: E501
        """PatchedTimeseriesLocalRain - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        # True if data is coming from API
        self._fetched_from_api = fetched_from_api

        self._url = None
        self._simulation = None
        self._offset = None
        self._values = None
        self._interpolate = None
        self._units = None
        self._diameter = None
        self._point = None
        self._uid = None
        self._id = None
        self._substances = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if simulation is not None:
            self.simulation = simulation
        if offset is not None:
            self.offset = offset
        if values is not None:
            self.values = values
        if interpolate is not None:
            self.interpolate = interpolate
        self.units = units
        if diameter is not None:
            self.diameter = diameter
        if point is not None:
            self.point = point
        if uid is not None:
            self.uid = uid
        if id is not None:
            self.id = id
        if substances is not None:
            self.substances = substances

    @property
    def url(self):
        """Gets the url of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The url of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this PatchedTimeseriesLocalRain.


        :param url: The url of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def simulation(self):
        """Gets the simulation of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The simulation of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: str
        """
        return self._simulation

    @simulation.setter
    def simulation(self, simulation):
        """Sets the simulation of this PatchedTimeseriesLocalRain.


        :param simulation: The simulation of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: str
        """

        self._simulation = simulation

    @property
    def offset(self):
        """Gets the offset of this PatchedTimeseriesLocalRain.  # noqa: E501

        offset of event in simulation in seconds  # noqa: E501

        :return: The offset of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PatchedTimeseriesLocalRain.

        offset of event in simulation in seconds  # noqa: E501

        :param offset: The offset of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                offset is not None and offset > 2147483647):  # noqa: E501
            self.__handle_validation_error("Invalid value for `offset`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                offset is not None and offset < 0):  # noqa: E501
            self.__handle_validation_error("Invalid value for `offset`, must be a value greater than or equal to `0`")  # noqa: E501

        self._offset = offset

    @property
    def values(self):
        """Gets the values of this PatchedTimeseriesLocalRain.  # noqa: E501

        Timeseries provided as a nested list. The inner list consists of exactly 2 values: timestamp, value  # noqa: E501

        :return: The values of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: list[list[float]]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this PatchedTimeseriesLocalRain.

        Timeseries provided as a nested list. The inner list consists of exactly 2 values: timestamp, value  # noqa: E501

        :param values: The values of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: list[list[float]]
        """
        if (self.local_vars_configuration.client_side_validation and
                values is not None and len(values) > 300):
            self.__handle_validation_error("Invalid value for `values`, number of items must be less than or equal to `300`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                values is not None and len(values) < 1):
            self.__handle_validation_error("Invalid value for `values`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._values = values

    @property
    def interpolate(self):
        """Gets the interpolate of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The interpolate of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: bool
        """
        return self._interpolate

    @interpolate.setter
    def interpolate(self, interpolate):
        """Sets the interpolate of this PatchedTimeseriesLocalRain.


        :param interpolate: The interpolate of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: bool
        """

        self._interpolate = interpolate

    @property
    def units(self):
        """Gets the units of this PatchedTimeseriesLocalRain.  # noqa: E501

        m/s is only option for now  * `m/s` - meter_per_second * `mm/h` - millimeter_per_hour * `mm/min` - millimeter_per_minute  # noqa: E501

        :return: The units of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: LocalRainUnitEnum
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this PatchedTimeseriesLocalRain.

        m/s is only option for now  * `m/s` - meter_per_second * `mm/h` - millimeter_per_hour * `mm/min` - millimeter_per_minute  # noqa: E501

        :param units: The units of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: LocalRainUnitEnum
        """

        self._units = units

    @property
    def diameter(self):
        """Gets the diameter of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The diameter of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: int
        """
        return self._diameter

    @diameter.setter
    def diameter(self, diameter):
        """Sets the diameter of this PatchedTimeseriesLocalRain.


        :param diameter: The diameter of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                diameter is not None and diameter > 2147483647):  # noqa: E501
            self.__handle_validation_error("Invalid value for `diameter`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                diameter is not None and diameter < -2147483648):  # noqa: E501
            self.__handle_validation_error("Invalid value for `diameter`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._diameter = diameter

    @property
    def point(self):
        """Gets the point of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The point of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: Point
        """
        return self._point

    @point.setter
    def point(self, point):
        """Sets the point of this PatchedTimeseriesLocalRain.


        :param point: The point of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: Point
        """

        self._point = point

    @property
    def uid(self):
        """Gets the uid of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The uid of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this PatchedTimeseriesLocalRain.


        :param uid: The uid of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: str
        """

        self._uid = uid

    @property
    def id(self):
        """Gets the id of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The id of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedTimeseriesLocalRain.


        :param id: The id of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def substances(self):
        """Gets the substances of this PatchedTimeseriesLocalRain.  # noqa: E501


        :return: The substances of this PatchedTimeseriesLocalRain.  # noqa: E501
        :rtype: list[ForcingSubstanceWithZone]
        """
        return self._substances

    @substances.setter
    def substances(self, substances):
        """Sets the substances of this PatchedTimeseriesLocalRain.


        :param substances: The substances of this PatchedTimeseriesLocalRain.  # noqa: E501
        :type: list[ForcingSubstanceWithZone]
        """

        self._substances = substances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def __handle_validation_error(self, message):
        # Only raise ValueError when not fetched from API
        try:
            from threedi_api_client import __version__ as VERSION
        except ImportError:
            VERSION = "unknown"

        if not self._fetched_from_api:
            raise ValueError(message + f" It is possible that the current threedi-api-client version ({VERSION}) is out of date: consult https://pypi.org/project/threedi-api-client/ and consider upgrading.")  # noqa: E501
        logger.warning(message + " Please update to the latest threedi-api-client version.")  # noqa: E501

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedTimeseriesLocalRain):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PatchedTimeseriesLocalRain):
            return True

        return self.to_dict() != other.to_dict()
