# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:09AM (UTC) on June 16, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


import logging
import pprint
import re  # noqa: F401

import six

from threedi_api_client.openapi.configuration import Configuration

logger = logging.getLogger(__name__)

class RevisionRasterTypeEnum(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DEM_FILE = "dem_file"
    EQUILIBRIUM_INFILTRATION_RATE_FILE = "equilibrium_infiltration_rate_file"
    FRICT_COEF_FILE = "frict_coef_file"
    INITIAL_GROUNDWATER_LEVEL_FILE = "initial_groundwater_level_file"
    INITIAL_WATERLEVEL_FILE = "initial_waterlevel_file"
    GROUNDWATER_HYDRO_CONNECTIVITY_FILE = "groundwater_hydro_connectivity_file"
    GROUNDWATER_IMPERVIOUS_LAYER_LEVEL_FILE = "groundwater_impervious_layer_level_file"
    INFILTRATION_DECAY_PERIOD_FILE = "infiltration_decay_period_file"
    INITIAL_INFILTRATION_RATE_FILE = "initial_infiltration_rate_file"
    LEAKAGE_FILE = "leakage_file"
    PHREATIC_STORAGE_CAPACITY_FILE = "phreatic_storage_capacity_file"
    HYDRAULIC_CONDUCTIVITY_FILE = "hydraulic_conductivity_file"
    POROSITY_FILE = "porosity_file"
    INFILTRATION_RATE_FILE = "infiltration_rate_file"
    MAX_INFILTRATION_CAPACITY_FILE = "max_infiltration_capacity_file"
    INTERCEPTION_FILE = "interception_file"
    VEGETATION_HEIGHT_FILE = "vegetation_height_file"
    VEGETATION_DRAG_COEFFICIENT_FILE = "vegetation_drag_coefficient_file"
    VEGETATION_STEM_COUNT_FILE = "vegetation_stem_count_file"
    VEGETATION_STEM_DIAMETER_FILE = "vegetation_stem_diameter_file"
    INITIAL_GROUNDWATER_CONCENTRATION_FILE = "initial_groundwater_concentration_file"

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    required_fields = [
    ]

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None, fetched_from_api=False):  # noqa: E501
        """RevisionRasterTypeEnum - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        # True if data is coming from API
        self._fetched_from_api = fetched_from_api
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def __handle_validation_error(self, message):
        # Only raise ValueError when not fetched from API
        try:
            from threedi_api_client import __version__ as VERSION
        except ImportError:
            VERSION = "unknown"

        if not self._fetched_from_api:
            raise ValueError(message + f" It is possible that the current threedi-api-client version ({VERSION}) is out of date: consult https://pypi.org/project/threedi-api-client/ and consider upgrading.")  # noqa: E501
        logger.warning(message + " Please update to the latest threedi-api-client version.")  # noqa: E501

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RevisionRasterTypeEnum):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RevisionRasterTypeEnum):
            return True

        return self.to_dict() != other.to_dict()
