# coding: utf-8

"""
    Rana simulation API

    Rana simulation API (latest stable version: v3)   Framework release: 3.4.104   Rana simulation core release: 3.7.2   deployed on:  10:29AM (UTC) on June 10, 2026  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: info@nelen-schuurmans.nl
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from threedi_api_client.openapi.configuration import Configuration


class RevisionRasterTypeEnum(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DEM_FILE = "dem_file"
    EQUILIBRIUM_INFILTRATION_RATE_FILE = "equilibrium_infiltration_rate_file"
    FRICT_COEF_FILE = "frict_coef_file"
    INITIAL_GROUNDWATER_LEVEL_FILE = "initial_groundwater_level_file"
    INITIAL_WATERLEVEL_FILE = "initial_waterlevel_file"
    GROUNDWATER_HYDRO_CONNECTIVITY_FILE = "groundwater_hydro_connectivity_file"
    GROUNDWATER_IMPERVIOUS_LAYER_LEVEL_FILE = "groundwater_impervious_layer_level_file"
    INFILTRATION_DECAY_PERIOD_FILE = "infiltration_decay_period_file"
    INITIAL_INFILTRATION_RATE_FILE = "initial_infiltration_rate_file"
    LEAKAGE_FILE = "leakage_file"
    PHREATIC_STORAGE_CAPACITY_FILE = "phreatic_storage_capacity_file"
    HYDRAULIC_CONDUCTIVITY_FILE = "hydraulic_conductivity_file"
    POROSITY_FILE = "porosity_file"
    INFILTRATION_RATE_FILE = "infiltration_rate_file"
    MAX_INFILTRATION_CAPACITY_FILE = "max_infiltration_capacity_file"
    INTERCEPTION_FILE = "interception_file"
    VEGETATION_HEIGHT_FILE = "vegetation_height_file"
    VEGETATION_DRAG_COEFFICIENT_FILE = "vegetation_drag_coefficient_file"
    VEGETATION_STEM_COUNT_FILE = "vegetation_stem_count_file"
    VEGETATION_STEM_DIAMETER_FILE = "vegetation_stem_diameter_file"
    INITIAL_GROUNDWATER_CONCENTRATION_FILE = "initial_groundwater_concentration_file"

    allowable_values = [DEM_FILE, EQUILIBRIUM_INFILTRATION_RATE_FILE, FRICT_COEF_FILE, INITIAL_GROUNDWATER_LEVEL_FILE, INITIAL_WATERLEVEL_FILE, GROUNDWATER_HYDRO_CONNECTIVITY_FILE, GROUNDWATER_IMPERVIOUS_LAYER_LEVEL_FILE, INFILTRATION_DECAY_PERIOD_FILE, INITIAL_INFILTRATION_RATE_FILE, LEAKAGE_FILE, PHREATIC_STORAGE_CAPACITY_FILE, HYDRAULIC_CONDUCTIVITY_FILE, POROSITY_FILE, INFILTRATION_RATE_FILE, MAX_INFILTRATION_CAPACITY_FILE, INTERCEPTION_FILE, VEGETATION_HEIGHT_FILE, VEGETATION_DRAG_COEFFICIENT_FILE, VEGETATION_STEM_COUNT_FILE, VEGETATION_STEM_DIAMETER_FILE, INITIAL_GROUNDWATER_CONCENTRATION_FILE]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None):  # noqa: E501
        """RevisionRasterTypeEnum - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration
        self.discriminator = None

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RevisionRasterTypeEnum):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RevisionRasterTypeEnum):
            return True

        return self.to_dict() != other.to_dict()
